development:
  adapter: postgresql
  encoding: utf8
  database: sample_app_development
  pool: 5
  username: rails
  password: rails
  host: 192.168.59.103
  port: 15432

test: &test
  adapter: postgresql
  encoding: utf8
  database: sample_app_test
  pool: 5
  username: rails
  password: rails
  host: 192.168.59.103
  port: 15432

production:
  adapter: postgresql
  encoding: utf8
  database: d4fv2j6g8tfc3k
  pool: 5
  username: ulqpkvpzryzhlr
  password: gSbjFpFLx9BzqGTuP2CfmgQ9yb
  host: ec2-54-225-130-164.compute-1.amazonaws.com
  port: 5432

cucumber:
  <<: *test